import time
from collections.abc import Callable
from datetime import UTC, datetime

from loguru import logger

from poseblend.exceptions import NoSceneGoodEnoughError
from poseblend.pipeline_steps.generate_blender_params import generate_blender_params
from poseblend.pipeline_steps.generate_t2i_images import generate_t2i_images
from poseblend.pipeline_steps.render_scenes import render_all_scenes
from poseblend.pipeline_steps.perform_edits import perform_all_edits
from poseblend.pipeline_steps.postprocess_renders import postprocess_all_renders
from poseblend.pipeline_steps.score_renders import score_all_renders
from poseblend.pipeline_steps.select_renders import select_renders
from poseblend.run_context import RunContext
from poseblend.schema.inputs.blender_objects import BlenderObjectRegistry
from poseblend.schema.inputs.config import PoseBlendConfig
from poseblend.schema.inputs.scene_spec import PoseBlendSceneSpec
from poseblend.schema.lm_outputs import BlenderSceneParams
from poseblend.schema.run_data import BlenderScene, GateDecision, RunData, SceneRender
from poseblend.utils import derive_seeds, load_yaml


async def _run_t2i_baseline(ctx: RunContext, run_start: float) -> RunData:
    run_data = ctx.run_data
    config = run_data.config

    step_start = time.time()
    results, lm_prompt = await generate_t2i_images(ctx, seed=config.seed)
    image_paths = [path for path, _ in results]
    prompts = [prompt for _, prompt in results]
    logger.info(
        f"Generated {len(image_paths)} T2I images "
        f"in {time.time() - step_start:.2f}s (total elapsed: {time.time() - run_start:.2f}s)"
    )

    faux_renders = [
        SceneRender(
            render_id=i,
            image_path=path,
            gate_decision=GateDecision(is_passing=True, reason="Generated by T2I model"),
        )
        for i, path in enumerate(image_paths)
    ]
    run_data.scenes = [
        BlenderScene(
            scene_id=1,
            seed=config.seed,
            params=BlenderSceneParams(placements=[]),
            renders=faux_renders,
            is_selected=True,
            gate_decision=GateDecision(is_passing=True, reason="Generated by T2I model"),
            prompt_used=lm_prompt,
        )
    ]
    ctx.on_run_data_changed()

    step_start = time.time()
    await perform_all_edits(
        ctx, faux_renders,
        starting_img_prompts=prompts,
        starting_img_model=config.t2i_model,
    )
    logger.info(
        f"Performed edits on {len(faux_renders)} edit chains "
        f"in {time.time() - step_start:.2f}s (total elapsed: {time.time() - run_start:.2f}s)"
    )
    logger.info(f"Total elapsed time: {time.time() - run_start:.2f}s")
    return run_data


async def _run_blender_pipeline(ctx: RunContext, run_start: float) -> RunData:
    run_data = ctx.run_data
    config = run_data.config
    n_scenes = config.num_blender_scenes
    n_renders = config.num_renders

    scene_seeds = derive_seeds(config.seed, n_scenes)

    step_start = time.time()
    params_list, lm_prompt = await generate_blender_params(ctx, seeds=scene_seeds)
    logger.info(
        f"Generated {n_scenes} blender params in {time.time() - step_start:.2f}s "
        f"(total elapsed: {time.time() - run_start:.2f}s)"
    )
    run_data.scenes = [
        BlenderScene(scene_id=i + 1, seed=seed, params=params, prompt_used=lm_prompt)
        for i, (params, seed) in enumerate(zip(params_list, scene_seeds))
    ]
    ctx.on_run_data_changed()

    step_start = time.time()
    await render_all_scenes(ctx)
    total_renders = n_scenes * n_renders
    logger.info(
        f"Rendered {total_renders} renders ({n_renders} renders for {n_scenes} scenes) "
        f"in {time.time() - step_start:.2f}s (total elapsed: {time.time() - run_start:.2f}s)"
    )

    step_start = time.time()
    postprocess_all_renders(ctx)
    ctx.on_run_data_changed()
    logger.info(
        f"Post-processed {total_renders} renders "
        f"in {time.time() - step_start:.2f}s (total elapsed: {time.time() - run_start:.2f}s)"
    )

    step_start = time.time()
    await score_all_renders(ctx)
    logger.info(
        f"Scored {total_renders} renders in {time.time() - step_start:.2f}s "
        f"(total elapsed: {time.time() - run_start:.2f}s)"
    )

    try:
        selected_renders = select_renders(ctx)
    except NoSceneGoodEnoughError as e:
        logger.error(f"Pipeline stopped: {e}")
        ctx.on_run_data_changed()
        logger.info(f"Total elapsed time: {time.time() - run_start:.2f}s")
        return run_data
    ctx.on_run_data_changed()

    step_start = time.time()
    await perform_all_edits(ctx, selected_renders)
    logger.info(
        f"Performed edits on {len(selected_renders)} edit chains "
        f"in {time.time() - step_start:.2f}s (total elapsed: {time.time() - run_start:.2f}s)"
    )
    logger.info(f"Total elapsed time: {time.time() - run_start:.2f}s")
    return run_data


async def run_poseblend(
    config: str | PoseBlendConfig,
    scene: str | PoseBlendSceneSpec,
    blender_object_data: str | BlenderObjectRegistry,
    on_update: Callable[[], None] | None = None,
    run_data: RunData | None = None,
) -> RunData:
    run_start = time.time()
    if run_data is None:
        if isinstance(config, str):
            config = PoseBlendConfig.model_validate(load_yaml(config))
        if isinstance(scene, str):
            scene = PoseBlendSceneSpec.model_validate(load_yaml(scene))
        if isinstance(blender_object_data, str):
            blender_object_data = BlenderObjectRegistry.model_validate(load_yaml(blender_object_data))
        run_id = datetime.now(tz=UTC).strftime("%Y%m%d_%H%M%S")
        run_data = RunData(
            config=config,
            scene_spec=scene,
            blender_object_registry=blender_object_data,
            run_id=run_id,
        )
    ctx = RunContext(run_data, on_update=on_update)

    if run_data.config.t2i_model:
        return await _run_t2i_baseline(ctx, run_start)
    else:
        return await _run_blender_pipeline(ctx, run_start)
